### ISSUE TITLE
reapp run error

### ISSUE THREAD

**Issue by xiaohuoni** [reapp/reapp#121]
npm install -g reapp 
reapp new [name]
reapp run

WARNING in ./app/app.js
Critical dependencies:
7:22-29 require function is used in a way in which dependencies cannot be static
ally extracted
 @ ./app/app.js 7:22-29

ERROR in ./~/reapp-ui/components/Button.js
Module not found: Error: Cannot resolve module 'react-addons-transition-group' i
n F:\test-reapp\node_modules\reapp-ui\components
 @ ./~/reapp-ui/components/Button.js 9:34-74

ERROR in ./~/reapp-ui/components/Typeahead.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/icons
/search.svg in F:\test-reapp\node_modules\reapp-ui\components
 @ ./~/reapp-ui/components/Typeahead.js 11:17-57

ERROR in ./~/reapp-ui/components/Typeahead.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/icons
/mic3.svg in F:\test-reapp\node_modules\reapp-ui\components
 @ ./~/reapp-ui/components/Typeahead.js 12:14-52

ERROR in ./~/reapp-ui/components/Typeahead.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/icons
/material-close.svg in F:\test-reapp\node_modules\reapp-ui\components
 @ ./~/reapp-ui/components/Typeahead.js 13:16-64

ERROR in ./~/reapp-ui/components/Typeahead.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/icons
/material-left.svg in F:\test-reapp\node_modules\reapp-ui\components
 @ ./~/reapp-ui/components/Typeahead.js 14:15-62

ERROR in ./~/reapp-ui/helpers/ripple/TouchRipple.js
Module not found: Error: Cannot resolve module 'react-addons-transition-group' i
n F:\test-reapp\node_modules\reapp-ui\helpers\ripple
 @ ./~/reapp-ui/helpers/ripple/TouchRipple.js 17:34-74

ERROR in ./~/reapp-ui/helpers/ripple/TouchRipple.js
Module not found: Error: Cannot resolve module 'react-addons-update' in F:\test-
reapp\node_modules\reapp-ui\helpers\ripple
 @ ./~/reapp-ui/helpers/ripple/TouchRipple.js 29:25-55

ERROR in ./~/reapp-ui/helpers/ripple/CircleRipple.js
Module not found: Error: Cannot resolve module 'recompose/shallowEqual' in F:\te
st-reapp\node_modules\reapp-ui\helpers\ripple
 @ ./~/reapp-ui/helpers/ripple/CircleRipple.js 29:29-62
webpack: bundle is now VALID.

Note: you have a require warning on your routes, this is ok!

Build took 2.986 seconds

**Comment by ickyrr** [comment]
Same problem here. Were you able to solve this?

**Comment by mabdurrehman** [comment]
Similar Problem
After running following commands 

npm install -g reapp 
reapp new myapp
reapp run 
```
Your app is running on http://localhost:3010

Building with Webpack...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3010
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```
**Then its terminates**
