### ISSUE TITLE
reapp new myapp broken on OS X

### ISSUE THREAD

**Issue by hipertracker** [reapp/reapp#5]
I can't create a project on my OS X 10.10.3 :(

``` 
$ node -v
v0.12.0

$ reapp -V
0.5.19

$ reapp new myapp
module.js:338
 throw err;
 ^
Error: Cannot find module '../build/Debug/nodegit'
 at Function.Module._resolveFilename (module.js:336:15)
 at Function.Module._load (module.js:278:25)
 at Module.require (module.js:365:17)
 at require (module.js:384:17)
 at Object.<anonymous> (/Users/hipertracker/.nvm/versions/node/v0.12.0/lib/node_modules/reapp/node_modules/nodegit/lib/nodegit.js:12:12)
 at Module._compile (module.js:460:26)
 at Object.Module._extensions..js (module.js:478:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Module.require (module.js:365:17)
```

**Comment by megalithic** [comment]
Ahh,@hipertracker, it MAY be with nvm. i had nvm with node installed via it and had all sorts of issues. I went back to homebrew node install and everything worked again (as of this morning).

**Comment by natew** [comment]
I've removed the dependency on nodegit, can you try installing again?

I've found errors on node global reinstalls sometimes that compile node-gyp like I do, if you get those you may want to run `rm -r ~/tmp` before reinstalling.

**Comment by csmpls** [comment]
i also cannot `reapp new` on OS X, but I'm experiencing a different issue:

```
$ node -v 
v0.12.0

$ npm -v
2.5.0

$ reapp --version
0.5.21

$ reapp new app

Creating new reapp folder for: app...
Running git clone --depth=1 git@github.com:reapp/reapp-starter.git /Users/ffff/Documents/app...

 Error
{ [Error: Command failed: /bin/sh -c git clone --depth=1 git@github.com:reapp/reapp-starter.git /Users/ffff/Documents/app
Cloning into '/Users/ffff/Documents/app'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
]
  killed: false,
  code: 128,
  signal: null,
  cmd: '/bin/sh -c git clone --depth=1 git@github.com:reapp/reapp-starter.git /Users/ffff/Documents/app' }

```

**Comment by megalithic** [comment]
@csmpls your issue looks specific to github permissions.. do you have a public key setup on github for your account? you may want to do that since the github repos used are the SSH variety that expect you to have said public key(s) setup.

**Comment by csmpls** [comment]
that solved it! thanks

**Comment by megalithic** [comment]
so glad to hear that; you're very welcome.

**Comment by natew** [comment]
Thanks all, closing but should be good reference.
